version: '3'
services:
  frontend:
    image: chandranikhil/frontend-image:latest
    restart: always
    ports:
      - '5173:5173'
    command: yarn run dev --host
  backend:
    image: chandranikhil/backend-image:latest
    restart: always
    ports:
      - '4000:4000'
    environment:
      - mongo_url = "mongodb+srv://nikhilpuppala03:Buncuski2BlCmygA@cluster0.6z92y.mongodb.net/"
      - jwtSecret = "ewrgfrtyjnyujtrtgyret"