version: '3'
services:
  container1:
    image: frontend-image
    ports:
      - "5173:5173"
    networks:
      - mynetwork
    depends_on:
      - container2

  container2:
    image: backend-image
    ports:
      - "4000:4000"
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  mynetwork: