apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 4000        # Service's port
      targetPort: 4000  # Pod's port
      nodePort: 30001   # Exposed NodePort
