apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30001
