apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 5173          # Service's port
    targetPort: 5173    # Pod's port
    nodePort: 30000     # Exposed NodePort
